import type { Metadata } from 'next';
import { ReduxProvider } from '@redux/provider';
import { SessionProvider } from 'next-auth/react';
import ThemeRegistry from '@theme/ThemeRegistry';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <ReduxProvider>
            <ThemeRegistry>{children}</ThemeRegistry>
          </ReduxProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
